name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Tools
        uses: ./.github/actions/setup-tools
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Check Cargo.lock
        run: cargo update -w --locked

      - name: Build
        run: just build

      - name: Test
        run: just test

      - name: Lint
        run: just lint

      - name: Check for uncommitted changes
        run: git diff --exit-code

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Tools
        uses: ./.github/actions/setup-tools
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Format
        run: just format-ci

  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Tools
        uses: ./.github/actions/setup-tools
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cargo audit
        run: cargo install cargo-audit

      - name: Audit
        run: cargo audit
